"""add_llm_provider_table

Revision ID: f057022da3a9
Revises: 0002_add_user_table
Create Date: 2026-03-21 21:30:02.081657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0003_add_llm_provider_table'
down_revision: Union[str, Sequence[str], None] = '0002_add_user_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('models', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_provider_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_provider_name'))

    op.drop_table('llm_provider')
    # ### end Alembic commands ###
